name: Website and Price Monitoring

on:
    push:
        branches: ["main", "feat/page_monitor"] # Test on pushes to these branches
    pull_request:
        branches: ["main"] # Test on PRs to main
    schedule:
        # Run price tracker twice daily (9 AM and 6 PM UTC)
        - cron: "0 9,18 * * *"
        # Run website monitor twice daily (9 AM and 6 PM UTC)
        - cron: "0 9,18 * * *"
    workflow_dispatch:
        inputs:
            project:
                description: "Which project to run"
                required: true
                default: "both"
                type: choice
                options:
                    - both
                    - price-tracker
                    - website-monitor

jobs:
    price-tracker:
        if: github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && (github.event.inputs.project == 'both' || github.event.inputs.project == 'price-tracker'))
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Debug secrets
              run: |
                  echo "Checking webhook configuration..."
                  if [ -n "$DISCORD_WEBHOOK" ]; then
                    echo "✅ DISCORD_WEBHOOK is set"
                  elif [ -n "$WEBHOOK_URL" ]; then
                    echo "✅ WEBHOOK_URL is set (fallback)"
                  else
                    echo "❌ No webhook secrets found"
                    echo "Available secrets should include: DISCORD_WEBHOOK or WEBHOOK_URL"
                    exit 1
                  fi
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

            - name: Run price tracker
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
              run: |
                  # Use DISCORD_WEBHOOK if available, otherwise fall back to WEBHOOK_URL
                  export DISCORD_WEBHOOK="${DISCORD_WEBHOOK:-$WEBHOOK_URL}"
                  cd projects/price-tracker
                  python reader.py

    website-monitor:
        if: github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && (github.event.inputs.project == 'both' || github.event.inputs.project == 'website-monitor'))
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  playwright install chromium

            - name: Debug secrets
              run: |
                  echo "Checking webhook configuration..."
                  if [ -n "$DISCORD_WEBHOOK" ]; then
                    echo "✅ DISCORD_WEBHOOK is set"
                  elif [ -n "$WEBHOOK_URL" ]; then
                    echo "✅ WEBHOOK_URL is set (fallback)"
                  else
                    echo "❌ No webhook secrets found"
                    echo "Available secrets should include: DISCORD_WEBHOOK or WEBHOOK_URL"
                    exit 1
                  fi
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

            - name: Run website monitor
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
              run: |
                  # Use DISCORD_WEBHOOK if available, otherwise fall back to WEBHOOK_URL
                  export DISCORD_WEBHOOK="${DISCORD_WEBHOOK:-$WEBHOOK_URL}"
                  cd projects/website-monitor
                  python monitor.py

            - name: Upload screenshots artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: website-screenshots
                  path: projects/website-monitor/screenshots/
                  retention-days: 7
