name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,12 * * *'  # This will run the workflow at 00:00 and 12:00 UTC every day

permissions:
  contents: read

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run price tracker
      run: |
        cd data
        cat rvrc-data.csv
        ls
        python3 src/csv-reader.py "https://discord.com/api/webhooks/1354888529351676025/W1cdc4I-3XO-nySm3CkKvHapoc3yzDYE1pZi173GZ1YkJYY6qDIwCihg54Pv16qUmstc"
