name: Python application

on:
  push:
    branches: [ "main", "dockerize" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,12 * * *'  # This will run the workflow at 00:00 and 12:00 UTC every day

permissions:
  contents: read

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: |
        docker build -t price-notification .
    - name: Run price tracker
      run: |
        echo "App variable is ${{vars.LEARN}}"
        docker run --rm -e DISCORD_WEBHOOK="${{secrets.WEBHOOK_URL}}" price-notification